meta_product_name: "Chien et maître"
meta_title: "Chien et maître - Participez à notre campagne"
meta_description: "Chien et maître - Participez à notre campagne"
meta_image: "meta/image.png"
twitter_account: "@chien-et-maitre"
