# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76fe6658440573a599f68afe54e4768060c1ce2fa1a8bf144e5c750a6b1510bacc379d7944fbc278caeda0806ff9e2f66a42af32b19efeb413dbc860736e8a73

test:
  secret_key_base: 484c81c120a9856f0bae9d470d0b1a1dc2bf4a6b9170c2d36b5016f05ddbd729d5a4a42ef0d8dd511b2ebccdce15e956891136d3ecc06bbc05e2145dc2afb276

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
